export const Selectors = {
  entrepriseCard: (name: string) => `button:has-text("${name}")`,
  sidebarLink: (name: string) => `a:has-text("${name}")`,
  pageTitle: (title: string) => `h1:has-text("${title}")`,
  submitButton: 'button[type="submit"]',
  saveButton: 'text=Enregistrer',
  createButton: 'text=Nouveau',
  deleteButton: 'text=Supprimer',
  cancelButton: 'text=Annuler',
  confirmButton: 'text=Confirmer',
  searchInput: 'input[placeholder*="Rechercher"]',
  tableRow: 'table tbody tr',
  modal: '[role="dialog"]',
  toast: '[role="alert"]',
  loadingSpinner: '.animate-spin',
  statutBadge: (statut: string) => `[class*="badge"]:has-text("${statut}")`,
  emptyState: 'text=Aucun',
  drawerBackdrop: '[class*="backdrop"]',
}
